[[constraint]]
  name = "github.com/cloudfoundry/cli"
  version = "6.32.0"

[[constraint]]
  branch = "master"
  name = "github.com/cloudfoundry/libbuildpack"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/pborman/getopt"

[[override]]
  name = "github.com/elazarl/goproxy"
  revision = "aacba83f36a55ac31cbb71c06547a328c0cd1604"
